import { typeOf, labelOf } from './fieldTypes.js';

// AUTO-GENERATED from the 360 Travel Scope-of-Work spec (80 masters).
const build = (pk, cols, fks = {}) =>
  cols.filter((c) => c !== pk).map((c) => {
    const base = { key: c, label: labelOf(c), type: typeOf(c) };
    return fks[c] ? { ...base, type: 'ref', ref: fks[c] } : base;
  });

export const MASTERS = {
  "company": {
    key: "company", label: "Company", menu: "Company",
    table: "tblCompanyMaster", pk: "intCompanyID", titleField: "strCompanyName",
    listColumns: ["strCompanyName", "strCompanyNickName", "strCompanyAddress", "intCityID"],
    fields: build("intCompanyID", ["intCompanyID", "strCompanyName", "strCompanyNickName", "strCompanyAddress", "intCityID", "strCompanyPostalCode", "strCompanyPhone", "strCompanyMobile", "strCompanyHelpline", "strCompanyOtherNo", "strCompanyEmail", "strCompanyWebsite", "dtCompanyFromYear", "dtCompanyToYear", "dtCompanyBooksBeginning", "strCompanyGSTIN", "dtCompanyGSTINDate", "strCompanyTaxNo", "dtCompanyTaxDate", "strCompanyPAN", "dtCompanyPANDate", "strCompanyTAN", "dtCompanyTANDate", "strCompanyCIN", "dtCompanyCINDate", "strCompanyRBILicenseNo", "dtCompanyRBILicenseIssueDate", "dtCompanyRBILicenseExpiryDate", "strCompanyBank", "strCompanySlogan", "strCompanyRemark", "strCompanyIATACode", "intCurrencyID", "strCompanyCode", "strCompanyYearCurrent", "strCompanyYearPrevious", "strCompanyYearNext", "intCompanyCustomerID", "strProductVersion", "bitCompanyActiveStatus", "strCompanyLegalTradeName"], {"intCityID": "city", "intCurrencyID": "currency"}),
  },
  "branch": {
    key: "branch", label: "Branch", menu: "Branch",
    table: "tblBranchMaster", pk: "intBranchID", titleField: "strBranchName",
    listColumns: ["intCompanyID", "strBranchName", "strBranchLanguage", "strBranchAmountInWord"],
    fields: build("intBranchID", ["intBranchID", "intCompanyID", "strBranchName", "strBranchLanguage", "strBranchAmountInWord", "strBranchLocation", "strBranchAddress", "intCityID", "strBranchPostalCode", "strBranchPhone", "strBranchMobile", "strBranchHelpline", "strBranchOtherNo", "strBranchEmail", "strBranchWebsite", "strBranchGSTIN", "dtBranchGSTINDate", "strBranchTaxNo", "dtBranchTaxDate", "strBranchPAN", "dtBranchPANDate", "strBranchTAN", "dtBranchTANDate", "strBranchCIN", "dtBranchCINDate", "strBranchRBILicenseNo", "dtBranchRBILicenseIssueDate", "dtBranchRBILicenseExpiryDate", "strBranchBank", "strBranchSlogan", "strBranchRemark", "strBranchIATACode", "intCurrencyID", "imgBranchSLogo", "imgBranchSign", "imgBranchFLogo", "imgBranchFooter", "bitBranchActiveStatus", "strBranchLegalTradeName"], {"intCompanyID": "company", "intCityID": "city", "intCurrencyID": "currency"}),
  },
  "currency": {
    key: "currency", label: "Currency", menu: "Currency",
    table: "tblCurrencyMaster", pk: "intCurrencyID", titleField: "strCurrencyName",
    listColumns: ["strCurrencyName", "intCountryID", "strCurrencySymbol", "strCurrencyISO"],
    fields: build("intCurrencyID", ["intCurrencyID", "strCurrencyName", "intCountryID", "strCurrencySymbol", "strCurrencyISO", "strCurrency", "strCurrencyUnit", "bitCurrencyRBIRate", "intCurrencyRatePer", "decCurrencyOpening", "decCurrencyOpeningRate", "decTravellerChequeOpening", "decTravellerChequeOpeningRate"], {"intCountryID": "country"}),
  },
  "country": {
    key: "country", label: "Country", menu: "Location",
    table: "tblCountryMaster", pk: "intCountryID", titleField: "strCountryName",
    listColumns: ["strCountryName", "decCurrencyLimit", "strCountryCode"],
    fields: build("intCountryID", ["intCountryID", "strCountryName", "decCurrencyLimit", "strCountryCode"], {}),
  },
  "state": {
    key: "state", label: "State", menu: "Location",
    table: "tblStateMaster", pk: "intStateID", titleField: "strStateName",
    listColumns: ["strStateName", "strStateZone", "strStateCode", "strStateShortName"],
    fields: build("intStateID", ["intStateID", "strStateName", "strStateZone", "strStateCode", "strStateShortName", "bitIsUnionTerritories"], {}),
  },
  "destination": {
    key: "destination", label: "Destination", menu: "Location",
    table: "tblDestinationMaster", pk: "intDestinationID", titleField: "strDestinationName",
    listColumns: ["strDestinationName", "strDestinationRemark"],
    fields: build("intDestinationID", ["intDestinationID", "strDestinationName", "tintDestinationType", "strDestinationRemark"], {}),
  },
  "city": {
    key: "city", label: "City", menu: "Location",
    table: "tblCityMaster", pk: "intCityID", titleField: "strCityName",
    listColumns: ["strCityName", "intCountryID", "intStateID", "intDestinationID"],
    fields: build("intCityID", ["intCityID", "strCityName", "intCountryID", "intStateID", "intDestinationID", "strCityLatitude", "strCityLongitude", "strCityRemark", "intCityOrder"], {"intCountryID": "country", "intStateID": "state", "intDestinationID": "destination"}),
  },
  "group": {
    key: "group", label: "Group", menu: "Group",
    table: "tblGroupMaster", pk: "intGroupID", titleField: "strGroupName",
    listColumns: ["strGroupName", "intGroupParentID", "strNatureOfGroup", "bitAffectGrossProfit"],
    fields: build("intGroupID", ["intGroupID", "strGroupName", "intGroupParentID", "strNatureOfGroup", "bitAffectGrossProfit", "bitMaintainBalanceBillwise", "bitUseforCalculation", "bitAddressRequired", "bitPhoneRequired", "bitMobileRequired", "bitEmailRequired", "bitHandleByRequired", "bitAgentRequired", "bitNatureofSupplyRequired", "bitPANRequired", "intPANLimit", "intGroupOrder", "strGroupTypeFlag", "bitConsiderForCashFlow", "bitDonotallowonaccount"], {}),
  },
  "account": {
    key: "account", label: "Account", menu: "Account",
    table: "tblAccountMaster", pk: "intAccountID", titleField: "strAccountName",
    listColumns: ["strAccountName", "strAccountAlias", "intGroupID", "intAccountAnalysisCode"],
    fields: build("intAccountID", ["intAccountID", "strAccountName", "strAccountAlias", "intGroupID", "intAccountAnalysisCode", "bitAccountActiveStatus", "dtAccountKYCDate", "bitAccountBlackListed", "strAccountRemark", "intAccountCreditLimit", "bitMaintainBalanceBillwise", "intAccountCreditDays", "strAccountAddress", "intCityID", "strAccountPostalCode", "strAccountPhone", "strAccountPhoneRes", "strAccountMobile", "strAccountFax", "strAccountEmail", "bitAccountAutoemail", "strAccountWebsite", "strAccountLocation", "strAccountAddressAlternate", "intNatureofSupplyID", "tintAccountGSTINType", "strAccountGSTIN", "dtAccountGSTINDate", "bitAccounteCOMOperator", "strAccounteCOMMerchantID", "strAccountReverseChargesPurchase", "strAccountReverseChargesSales", "strAccountCenvatCredit", "strAccountTaxNo", "decAccountRefundableTaxPer", "strAccountDoNotCalTax", "tintAccountTaxRoundMethod", "strAccountNameofResponsible", "strAccountPAN", "strAccountTAN", "bitAccountTDSExempt", "intAccountTDSLimit", "decAccountTDSPer", "tintAccountTDSRoundMethod", "tintAccountTACRoundMethod", "tintAccountForexAgencyType", "strAccountRBILicenseNo", "dtAccountRBILicenseIssueDate", "dtAccountRBILicenseExpiryDate", "strAccountBank", "strAccountPerson", "strAccountPersonMobile", "intAccountHandleByID", "intAccountAllotedToID", "intAccountSubAgentID", "intAccountReferenceID", "strAccountPrintingNotes", "tintAccountPrintDetailAirTax", "tintAccountPrintDetailOtherTax", "tintAccountAgencyType", "strAccountAgencyCode", "bitAccountIsTDS", "tintAccountTDSType", "bitAccountIsForexGainLoss", "decAccountDepreciationPer", "strAccountAirCode", "strAccountAirPrefix", "bitAccountLCCCarrier", "strAccountTrainNo", "intAccountPrevYearID", "intObjectID", "strAccountAadhar", "decAccountTCSPer", "tintAccountTCSRoundMethod", "strAccountLegalTradeName", "dtAccountBirthDate", "strAccountPrintingName", "strAccountMSMENo"], {"intGroupID": "group", "intCityID": "city", "intNatureofSupplyID": "natureofSupply", "intObjectID": "object"}),
  },
  "contactHead": {
    key: "contactHead", label: "Contact", menu: "Contact",
    table: "tblContactHead", pk: "intContactHeadID", titleField: "strContactHeadName",
    listColumns: ["intAccountID", "strContactHeadName", "strContactHeadEmail", "intProfessionID"],
    fields: build("intContactHeadID", ["intContactHeadID", "intAccountID", "tintContactHeadType", "strContactHeadName", "tintContactHeadGender", "strContactHeadEmail", "dtContactHeadBirthDate", "dtContactHeadAnniversaryDate", "intProfessionID", "intReligionID", "intReferenceAccountID", "strContactHeadContactNo", "strContactHeadWhatsAppNumber", "strContactHeadAddress", "intCityID", "strContactHeadPostalCode", "strContactHeadPassportNo", "strContactHeadIssuePlace", "intNationalityID", "dtContactHeadPassportIssueDate", "dtContactHeadPassportExpiryDate", "strContactHeadPAN", "intProofID", "strContactHeadProofNumber", "intContactHeadFoodID", "strContactHeadFrequentNo", "intEmployeeID", "intVehModelID", "dtContactHeadKYCDate", "strContactHeadNotes", "intUserID", "intContactHeadFilterID1", "intContactHeadFilterID2", "dtContactHeadEntryDate"], {"intAccountID": "account", "intProfessionID": "profession", "intReligionID": "religion", "intCityID": "city", "intNationalityID": "nationality", "intProofID": "proof", "intEmployeeID": "employee", "intVehModelID": "vehModel", "intUserID": "permission"}),
  },
  "bank": {
    key: "bank", label: "Customer Bank", menu: "Customer Bank",
    table: "tblBankMaster", pk: "intBankID", titleField: "strBankName",
    listColumns: ["strBankName"],
    fields: build("intBankID", ["intBankID", "strBankName"], {}),
  },
  "religion": {
    key: "religion", label: "Religion", menu: "CRM",
    table: "tblReligionMaster", pk: "intReligionID", titleField: "strReligionName",
    listColumns: ["strReligionName"],
    fields: build("intReligionID", ["intReligionID", "strReligionName"], {}),
  },
  "relation": {
    key: "relation", label: "Relation", menu: "CRM",
    table: "tblRelationMaster", pk: "intRelationID", titleField: "strRelationName",
    listColumns: ["strRelationName"],
    fields: build("intRelationID", ["intRelationID", "strRelationName"], {}),
  },
  "nationality": {
    key: "nationality", label: "Nationality", menu: "CRM",
    table: "tblNationalityMaster", pk: "intNationalityID", titleField: "strNationalityName",
    listColumns: ["strNationalityName"],
    fields: build("intNationalityID", ["intNationalityID", "strNationalityName"], {}),
  },
  "proof": {
    key: "proof", label: "Proof", menu: "CRM",
    table: "tblProofMaster", pk: "intProofID", titleField: "strProofName",
    listColumns: ["strProofName"],
    fields: build("intProofID", ["intProofID", "strProofName"], {}),
  },
  "profession": {
    key: "profession", label: "Profession", menu: "CRM",
    table: "tblProfessionMaster", pk: "intProfessionID", titleField: "strProfessionName",
    listColumns: ["strProfessionName"],
    fields: build("intProfessionID", ["intProfessionID", "strProfessionName"], {}),
  },
  "reference": {
    key: "reference", label: "Reference", menu: "CRM",
    table: "tblReferenceMaster", pk: "intReferenceID", titleField: "strReferenceName",
    listColumns: ["strReferenceName"],
    fields: build("intReferenceID", ["intReferenceID", "strReferenceName"], {}),
  },
  "insuranceType": {
    key: "insuranceType", label: "Insurance Type", menu: "CRM",
    table: "tblInsuranceTypeMaster", pk: "intInsuranceTypeID", titleField: "strInsuranceTypeName",
    listColumns: ["strInsuranceTypeName"],
    fields: build("intInsuranceTypeID", ["intInsuranceTypeID", "strInsuranceTypeName"], {}),
  },
  "food": {
    key: "food", label: "Food", menu: "CRM",
    table: "tblFoodMaster", pk: "intFoodID", titleField: "strFoodName",
    listColumns: ["strFoodName"],
    fields: build("intFoodID", ["intFoodID", "strFoodName"], {}),
  },
  "action": {
    key: "action", label: "Action", menu: "CRM",
    table: "tblActionMaster", pk: "intActionID", titleField: "strActionName",
    listColumns: ["strActionName"],
    fields: build("intActionID", ["intActionID", "strActionName"], {}),
  },
  "status": {
    key: "status", label: "Status", menu: "CRM",
    table: "tblStatusMaster", pk: "intStatusID", titleField: "strStatusName",
    listColumns: ["strStatusName"],
    fields: build("intStatusID", ["intStatusID", "strStatusName"], {}),
  },
  "supplierHead": {
    key: "supplierHead", label: "Supplier", menu: "CRM",
    table: "tblSupplierHead", pk: "intSupplierHeadID", titleField: "intSupplierHeadID",
    listColumns: ["intAccountID"],
    fields: build("intSupplierHeadID", ["intSupplierHeadID", "intAccountID"], {"intAccountID": "account"}),
  },
  "tour": {
    key: "tour", label: "Tour Master", menu: "Tour",
    table: "tblTourMaster", pk: "intTourID", titleField: "strTourName",
    listColumns: ["strTourName", "strTourIncludes", "strTourExcludes", "strTourTerms"],
    fields: build("intTourID", ["intTourID", "strTourName", "tintTourDestination", "strTourIncludes", "strTourExcludes", "strTourTerms", "strTourNotes", "strTourCancellationPolicy", "strTourRefund", "strTourJurisdiction"], {}),
  },
  "tourCategory": {
    key: "tourCategory", label: "Tour Category", menu: "Tour",
    table: "tblTourCategoryMaster", pk: "intTourCategoryID", titleField: "strTourCategoryName",
    listColumns: ["strTourCategoryName"],
    fields: build("intTourCategoryID", ["intTourCategoryID", "strTourCategoryName"], {}),
  },
  "tourOptions": {
    key: "tourOptions", label: "Tour Options", menu: "Tour",
    table: "tblTourOptionsMaster", pk: "intTourOptionsID", titleField: "strTourOptionsName",
    listColumns: ["strTourOptionsName", "intTourOptionsOrder"],
    fields: build("intTourOptionsID", ["intTourOptionsID", "strTourOptionsName", "intTourOptionsOrder"], {}),
  },
  "touristCategory": {
    key: "touristCategory", label: "Tourist Category", menu: "Tour",
    table: "tblTouristCategoryMaster", pk: "intTouristCategoryID", titleField: "strTouristCategoryName",
    listColumns: ["strTouristCategoryName"],
    fields: build("intTouristCategoryID", ["intTouristCategoryID", "strTouristCategoryName"], {}),
  },
  "property": {
    key: "property", label: "Property", menu: "Tour",
    table: "tblPropertyMaster", pk: "intPropertyID", titleField: "strPropertyName",
    listColumns: ["strPropertyName"],
    fields: build("intPropertyID", ["intPropertyID", "strPropertyName"], {}),
  },
  "roomType": {
    key: "roomType", label: "Room Type", menu: "Tour",
    table: "tblRoomTypeMaster", pk: "intRoomTypeID", titleField: "strRoomTypeName",
    listColumns: ["strRoomTypeName"],
    fields: build("intRoomTypeID", ["intRoomTypeID", "strRoomTypeName"], {}),
  },
  "mealPlan": {
    key: "mealPlan", label: "Meal Plan", menu: "Tour",
    table: "tblMealPlanMaster", pk: "intMealPlanID", titleField: "strMealPlanName",
    listColumns: ["strMealPlanName", "strMealPlanDescription", "bitBreakFast", "bitLunch"],
    fields: build("intMealPlanID", ["intMealPlanID", "strMealPlanName", "strMealPlanDescription", "bitBreakFast", "bitLunch", "bitDinner", "intMealPlanOrder"], {}),
  },
  "facility": {
    key: "facility", label: "Facility", menu: "Tour",
    table: "tblFacilityMaster", pk: "intFacilityID", titleField: "strFacilityName",
    listColumns: ["strFacilityName"],
    fields: build("intFacilityID", ["intFacilityID", "strFacilityName"], {}),
  },
  "hotelHead": {
    key: "hotelHead", label: "Hotel", menu: "Tour",
    table: "tblHotelHead", pk: "intHotelHeadID", titleField: "strHotelInTime",
    listColumns: ["intAccountID", "intPropertyID", "intHotelNoofRoom", "strHotelInTime"],
    fields: build("intHotelHeadID", ["intHotelHeadID", "intAccountID", "intPropertyID", "tintHotelStarCategory", "intHotelNoofRoom", "strHotelInTime", "strHotelOutTime", "tintHotelChildAgeFrom", "tintHotelChildAgeTo", "tintHotelTariffType", "bitHotelActiveStatus", "tintHotelSeasonIncludes", "tintHotelTaxIn", "tintHotelWeekEnd", "bitHotelRateVerified", "intUserID", "intBranchID"], {"intAccountID": "account", "intPropertyID": "property", "intUserID": "permission", "intBranchID": "dataLocking"}),
  },
  "excursionType": {
    key: "excursionType", label: "Excursion Type", menu: "Tour",
    table: "tblExcursionTypeMaster", pk: "intExcursionTypeID", titleField: "strExcursionTypeName",
    listColumns: ["strExcursionTypeName", "intCountryID", "strExcursionTypeRemark"],
    fields: build("intExcursionTypeID", ["intExcursionTypeID", "strExcursionTypeName", "tintExcursionTypeFor", "intCountryID", "strExcursionTypeRemark"], {"intCountryID": "country"}),
  },
  "excursion": {
    key: "excursion", label: "Excursion", menu: "Tour",
    table: "tblExcursionMaster", pk: "intExcursionID", titleField: "strExcursionName",
    listColumns: ["strExcursionName", "intExcursionTypeID", "intCityID", "intExcursionDaysforVisa"],
    fields: build("intExcursionID", ["intExcursionID", "strExcursionName", "intExcursionTypeID", "intCityID", "intExcursionDaysforVisa", "intExcursionQuotaforVisa", "dtExcursionAppliedfrom", "tintExcursionChargesPer", "decExcursionAdultCharges", "decExcursionChildCharges", "decExcursionInfantCharges", "decExcursionTripCharges", "intCurrencyID", "strExcursionRemark"], {"intExcursionTypeID": "excursionType", "intCityID": "city", "intCurrencyID": "currency"}),
  },
  "transport": {
    key: "transport", label: "Transport", menu: "Tour",
    table: "tblTransportMaster", pk: "intTransportID", titleField: "strTransportReferenceNo",
    listColumns: ["intTransportFromCityID", "intTransportToCityID", "strTransportReferenceNo", "strTransportClass"],
    fields: build("intTransportID", ["intTransportID", "tintTransportMode", "intTransportFromCityID", "intTransportToCityID", "dtTransportAppliedfrom", "strTransportReferenceNo", "strTransportClass", "decTransportAdultCharges", "decTransportChildWSCharges", "decTransportChildNSCharges", "decTransportInfantCharges", "intCurrencyID", "strTransportRemark"], {"intCurrencyID": "currency"}),
  },
  "dayPlan": {
    key: "dayPlan", label: "Day Plan", menu: "Tour",
    table: "tblDayPlanMaster", pk: "intDayPlanID", titleField: "strDayPlanTitle",
    listColumns: ["intCityID", "strDayPlanTitle", "strDayPlanDetail", "intObjectID"],
    fields: build("intDayPlanID", ["intDayPlanID", "tintDayPlanDay", "intCityID", "strDayPlanTitle", "strDayPlanDetail", "intObjectID"], {"intCityID": "city", "intObjectID": "object"}),
  },
  "vehBrand": {
    key: "vehBrand", label: "Vehicle Brand", menu: "Rent A Cab",
    table: "tblVehBrandMaster", pk: "intVehBrandID", titleField: "strVehBrandName",
    listColumns: ["strVehBrandName"],
    fields: build("intVehBrandID", ["intVehBrandID", "strVehBrandName"], {}),
  },
  "vehType": {
    key: "vehType", label: "Vehicle Type", menu: "Rent A Cab",
    table: "tblVehTypeMaster", pk: "intVehTypeID", titleField: "strVehTypeName",
    listColumns: ["strVehTypeName"],
    fields: build("intVehTypeID", ["intVehTypeID", "strVehTypeName"], {}),
  },
  "vehModel": {
    key: "vehModel", label: "Vehicle Model", menu: "Rent A Cab",
    table: "tblVehModelMaster", pk: "intVehModelID", titleField: "strVehModelName",
    listColumns: ["strVehModelName", "intVehBrandID", "intVehTypeID", "intPaxCapacity"],
    fields: build("intVehModelID", ["intVehModelID", "strVehModelName", "intVehBrandID", "intVehTypeID", "intPaxCapacity"], {"intVehBrandID": "vehBrand", "intVehTypeID": "vehType"}),
  },
  "veh": {
    key: "veh", label: "Vehicle", menu: "Rent A Cab",
    table: "tblVehMaster", pk: "intVehID", titleField: "strVehNumber",
    listColumns: ["strVehNumber", "intVehModelYear", "intVehModelID", "strVehEngineNumber"],
    fields: build("intVehID", ["intVehID", "strVehNumber", "dtVehRegistrationDate", "intVehModelYear", "intVehModelID", "tintVehFuelType", "strVehEngineNumber", "dtVehPUCDueDate", "strVehChasisNumber", "dtVehFitnessDueDate", "strVehInsuranceNumber", "dtVehInsuranceDueDate", "strVehPermitNumber", "dtVehPermitDueDate", "decVehTAXAmount", "dtVehTAXDueDate", "strVehApprovalNumber", "dtVehApprovalDueDate", "bitVehIsSold"], {"intVehModelID": "vehModel"}),
  },
  "vehTariffHead": {
    key: "vehTariffHead", label: "Vehicle Tariff", menu: "Rent A Cab",
    table: "tblVehTariffHead", pk: "intVehTariffHeadID", titleField: "intVehTariffHeadID",
    listColumns: ["intAccountID", "intCityID", "bitIsVehTariffHeadDeactive", "bitIsVehTariffHeadNightHaltActual"],
    fields: build("intVehTariffHeadID", ["intVehTariffHeadID", "intAccountID", "intCityID", "dtVehTariffHeadDate", "bitIsVehTariffHeadDeactive", "tintVehTariffHeadNightHaltfrom", "tintVehTariffHeadNightHaltfromII", "bitIsVehTariffHeadNightHaltActual", "bitIsVehTariffHeadOnMaximum", "intUserID"], {"intAccountID": "account", "intCityID": "city", "intUserID": "permission"}),
  },
  "vehVendorHead": {
    key: "vehVendorHead", label: "Vendor", menu: "Rent A Cab",
    table: "tblVehVendorHead", pk: "intVehVendorHeadID", titleField: "intVehVendorHeadID",
    listColumns: ["intAccountID", "intUserID", "bitIsAttachedVendor"],
    fields: build("intVehVendorHeadID", ["intVehVendorHeadID", "intAccountID", "intUserID", "bitIsAttachedVendor"], {"intAccountID": "account", "intUserID": "permission"}),
  },
  "vehMaintenanceHead": {
    key: "vehMaintenanceHead", label: "Vehicle Maintenance", menu: "Rent A Cab",
    table: "tblVehMaintenanceHead", pk: "intVehMaintenanceHeadID", titleField: "strVehMaintenanceHeadPrefix",
    listColumns: ["strVehMaintenanceHeadPrefix", "intVehMaintenanceHeadNumber", "strVehMaintenanceHeadRefNumber", "intCreditAccountID"],
    fields: build("intVehMaintenanceHeadID", ["intVehMaintenanceHeadID", "strVehMaintenanceHeadPrefix", "intVehMaintenanceHeadNumber", "dtVehMaintenanceHeadDate", "strVehMaintenanceHeadRefNumber", "intCreditAccountID", "intDebitAccountID", "strVehMaintenanceHeadNotes", "decVehMaintenanceHeadOtherAmt", "decVehMaintenanceHeadRoundOffAmt", "decVehMaintenanceHeadNetAmt", "intAddUserID", "intEditUserID", "intObjectID", "intBranchID", "intVehMaintenanceHeadYear"], {"intObjectID": "object", "intBranchID": "dataLocking"}),
  },
  "vehMaintenanceParts": {
    key: "vehMaintenanceParts", label: "Vehicle Parts", menu: "Rent A Cab",
    table: "tblVehMaintenancePartsMaster", pk: "intVehMaintenancePartsID", titleField: "strVehMaintenancePartsName",
    listColumns: ["strVehMaintenancePartsName"],
    fields: build("intVehMaintenancePartsID", ["intVehMaintenancePartsID", "strVehMaintenancePartsName", "tintVehMaintenancePartsType"], {}),
  },
  "vehFuelRate": {
    key: "vehFuelRate", label: "Vehicle Fuel Rate", menu: "Rent A Cab",
    table: "tblVehFuelRateMaster", pk: "intVehFuelRateID", titleField: "intVehFuelRateID",
    listColumns: ["decVehFuelRate"],
    fields: build("intVehFuelRateID", ["intVehFuelRateID", "dtVehFuelRateDateFrom", "tintVehFuelType", "decVehFuelRate"], {}),
  },
  "vehMinute": {
    key: "vehMinute", label: "Vehicle Minute Setting", menu: "Rent A Cab",
    table: "tblVehMinuteMaster", pk: "intVehMinuteID", titleField: "intVehMinuteID",
    listColumns: [],
    fields: build("intVehMinuteID", ["intVehMinuteID", "tintVehMinuteFrom", "tintVehMinuteTo", "tintVehMinute", "tintVehMinutefor"], {}),
  },
  "cRS": {
    key: "cRS", label: "CRS", menu: "Ticket",
    table: "tblCRSMaster", pk: "intCRSID", titleField: "strCRSName",
    listColumns: ["strCRSName"],
    fields: build("intCRSID", ["intCRSID", "strCRSName", "tintCRSType"], {}),
  },
  "salesPointHead": {
    key: "salesPointHead", label: "Sales Point", menu: "Ticket",
    table: "tblSalesPointHead", pk: "intSalesPointHeadID", titleField: "intSalesPointHeadID",
    listColumns: ["intCRSID", "intBranchID", "intUserID"],
    fields: build("intSalesPointHeadID", ["intSalesPointHeadID", "intCRSID", "intBranchID", "intUserID"], {"intCRSID": "cRS", "intBranchID": "dataLocking", "intUserID": "permission"}),
  },
  "quota": {
    key: "quota", label: "Quota", menu: "Ticket",
    table: "tblQuotaMaster", pk: "intQuotaID", titleField: "strQuotaName",
    listColumns: ["strQuotaName"],
    fields: build("intQuotaID", ["intQuotaID", "strQuotaName"], {}),
  },
  "railClass": {
    key: "railClass", label: "Railway Class", menu: "Ticket",
    table: "tblRailClassMaster", pk: "intRailClassID", titleField: "strRailClassName",
    listColumns: ["strRailClassName", "decRTSACharge", "decIRCTCCharge"],
    fields: build("intRailClassID", ["intRailClassID", "strRailClassName", "tintRailClassType", "decRTSACharge", "decIRCTCCharge"], {}),
  },
  "busType": {
    key: "busType", label: "Bus Type", menu: "Ticket",
    table: "tblBusTypeMaster", pk: "intBusTypeID", titleField: "strBusTypeName",
    listColumns: ["strBusTypeName"],
    fields: build("intBusTypeID", ["intBusTypeID", "strBusTypeName"], {}),
  },
  "narration": {
    key: "narration", label: "Narration", menu: "Auxiliary",
    table: "tblNarrationMaster", pk: "intNarrationID", titleField: "strNarrationDetail",
    listColumns: ["strNarrationDetail", "strObjectID"],
    fields: build("intNarrationID", ["intNarrationID", "strNarrationDetail", "strObjectID"], {}),
  },
  "voucherNewReference": {
    key: "voucherNewReference", label: "Voucher New Reference", menu: "Auxiliary",
    table: "tblVoucherNewReference", pk: "intVoucherNewReferenceID", titleField: "strVoucherNewReferenceName",
    listColumns: ["strVoucherNewReferenceName"],
    fields: build("intVoucherNewReferenceID", ["intVoucherNewReferenceID", "strVoucherNewReferenceName"], {}),
  },
  "submissionStage": {
    key: "submissionStage", label: "Submission Stage", menu: "Auxiliary",
    table: "tblSubmissionStageMaster", pk: "intSubmissionStageID", titleField: "strSubmissionStageName",
    listColumns: ["strSubmissionStageName", "strSubmissionStageDescription", "intSubmissionStageOrder"],
    fields: build("intSubmissionStageID", ["intSubmissionStageID", "strSubmissionStageName", "strSubmissionStageDescription", "intSubmissionStageOrder"], {}),
  },
  "department": {
    key: "department", label: "Department", menu: "Employee Detail",
    table: "tblDepartmentMaster", pk: "intDepartmentID", titleField: "strDepartmentName",
    listColumns: ["strDepartmentName", "bitRelatedtoSales"],
    fields: build("intDepartmentID", ["intDepartmentID", "strDepartmentName", "bitRelatedtoSales"], {}),
  },
  "designation": {
    key: "designation", label: "Designation", menu: "Employee Detail",
    table: "tblDesignationMaster", pk: "intDesignationID", titleField: "strDesignationName",
    listColumns: ["strDesignationName"],
    fields: build("intDesignationID", ["intDesignationID", "strDesignationName"], {}),
  },
  "employee": {
    key: "employee", label: "Employee", menu: "Employee Detail",
    table: "tblEmployeeMaster", pk: "intEmployeeID", titleField: "strEmployeeName",
    listColumns: ["strEmployeeName", "strEmployeeAddress", "intCityID", "strEmployeeMobile"],
    fields: build("intEmployeeID", ["intEmployeeID", "strEmployeeName", "strEmployeeAddress", "intCityID", "strEmployeeMobile", "strEmployeeEmail", "dtEmployeeBirthDate", "dtEmployeeAnniversaryDate", "intDepartmentID", "intDesignationID", "dtEmployeeJoinDate", "dtEmployeeResignDate", "strEmployeeLicense", "dtEmployeeLicenseDate", "strEmployeeBadge", "dtEmployeeBadgeDate", "decEmployeeBasicSalary", "intEmployeeOpLeave", "bitRBIAuthority", "strEmployeeSignAmadeus", "strEmployeeSignGalileo", "strEmployeeSignAbacus", "strEmployeeBank", "dtEmployeeKYCDate"], {"intCityID": "city", "intDepartmentID": "department", "intDesignationID": "designation"}),
  },
  "user": {
    key: "user", label: "User", menu: "User Setting",
    table: "tblUserMaster", pk: "intUserID", titleField: "strUserName",
    listColumns: ["strUserName", "strUserPassword", "bitUserFirstLogin", "strUserDisplayName"],
    fields: build("intUserID", ["intUserID", "strUserName", "strUserPassword", "bitUserFirstLogin", "strUserDisplayName", "strUserContact", "strUserWhatsAppNumber", "strUserEmail", "strUserEmailUserName", "strUserEmailPassword", "bitUserAdminAccount", "bitUserAdminCRM", "strUserDashboardRights", "strUserChecklistRights", "strUserAuxiliaryRights", "strUserApprovalControl", "bitUserDataRestore", "bitUserDataBackup", "bitUserStatus", "intBranchID"], {"intBranchID": "dataLocking"}),
  },
  "teamConfiguration": {
    key: "teamConfiguration", label: "Team Configuration", menu: "User Setting",
    table: "tblTeamConfiguration", pk: "intLeaderUserID", titleField: "intLeaderUserID",
    listColumns: ["intTeamUserID"],
    fields: build("intLeaderUserID", ["intLeaderUserID", "intTeamUserID"], {}),
  },
  "object": {
    key: "object", label: "Object", menu: "User Setting",
    table: "tblObjectMaster", pk: "intObjectID", titleField: "strObjectName",
    listColumns: ["strObjectName", "strObjectBooks", "bitObjectApprovalControl", "bitObjectDateLocking"],
    fields: build("intObjectID", ["intObjectID", "strObjectName", "tintObjectType", "strObjectBooks", "bitObjectApprovalControl", "bitObjectDateLocking", "tintObjectBooksOrder", "strObjectPermission", "intObjectOrder"], {}),
  },
  "permission": {
    key: "permission", label: "Permission", menu: "User Setting",
    table: "tblPermissionMaster", pk: "intUserID", titleField: "strPermission",
    listColumns: ["intObjectID", "strPermission"],
    fields: build("intUserID", ["intUserID", "intObjectID", "strPermission"], {"intObjectID": "object"}),
  },
  "webLoginHead": {
    key: "webLoginHead", label: "Web Login", menu: "User Setting",
    table: "tblWebLoginHead", pk: "intWebLoginHeadID", titleField: "strWebLoginHeadCompany",
    listColumns: ["intAccountID", "strWebLoginHeadCompany", "strWebLoginHeadName", "strWebLoginHeadContact"],
    fields: build("intWebLoginHeadID", ["intWebLoginHeadID", "intAccountID", "strWebLoginHeadCompany", "strWebLoginHeadName", "strWebLoginHeadContact", "strWebLoginHeadEmail", "intBranchID"], {"intAccountID": "account", "intBranchID": "dataLocking"}),
  },
  "reminderHead": {
    key: "reminderHead", label: "Reminder", menu: "Reminder",
    table: "tblReminderHead", pk: "intReminderHeadID", titleField: "strReminderHeadfor",
    listColumns: ["strReminderHeadfor", "bitReminderHeadActiveStatus", "intUserID", "intBranchID"],
    fields: build("intReminderHeadID", ["intReminderHeadID", "strReminderHeadfor", "dtReminderHeadDueDate", "tintReminderHeadBeforeDay", "tintReminderHeadRemindDay", "bitReminderHeadActiveStatus", "intUserID", "intBranchID"], {"intUserID": "permission", "intBranchID": "dataLocking"}),
  },
  "accountSetupHead": {
    key: "accountSetupHead", label: "Options", menu: "Setup",
    table: "tblAccountSetupHead", pk: "intAccountSetupHeadID", titleField: "intAccountSetupHeadID",
    listColumns: ["intBranchID"],
    fields: build("intAccountSetupHeadID", ["intAccountSetupHeadID", "dtAccountSetupHeadDate", "intBranchID"], {"intBranchID": "dataLocking"}),
  },
  "service": {
    key: "service", label: "Service", menu: "Setup",
    table: "tblServiceMaster", pk: "intServiceID", titleField: "strServiceName",
    listColumns: ["strServiceName", "strServiceGoodsCode", "strServiceGoodsIICode", "strServiceGSTReimbursement"],
    fields: build("intServiceID", ["intServiceID", "tintServiceGoodsType", "strServiceName", "strServiceGoodsCode", "strServiceGoodsIICode", "strServiceGSTReimbursement", "bitServicePrintK3Tax", "strServiceGSTSalesNote", "bitServiceGSTSalesTaxSummary", "strServiceGSTSalesReturnNote", "bitServiceGSTSalesReturnTaxSummary", "intServiceOrder", "tintServiceTCSOn"], {}),
  },
  "natureofSupply": {
    key: "natureofSupply", label: "Goods", menu: "Setup",
    table: "tblNatureofSupplyMaster", pk: "intNatureofSupplyID", titleField: "strNatureofSupplyName",
    listColumns: ["strNatureofSupplyName", "strNatureofSupplyfor", "strNatureofSupplySalesPrefix", "intNatureofSupplySalesAmountLessthen"],
    fields: build("intNatureofSupplyID", ["intNatureofSupplyID", "strNatureofSupplyName", "tintNatureofSupplyB2BB2C", "tintNatureofSupplyInterIntraState", "tintNatureofSupplyPayType", "strNatureofSupplyfor", "tintNatureofSupplyTaxTypeof", "strNatureofSupplySalesPrefix", "dtNatureofSupplyAppliedfrom", "intNatureofSupplySalesAmountLessthen", "tintNatureofSupplySalesValidation", "strNatureofSupplySalesValidation", "strNatureofSupplyGSTSalesNote", "strNatureofSupplyGSTSalesReturnNote", "intNatureofSupplyPurchaseAmountLessthen", "tintNatureofSupplyPurchaseValidation", "strNatureofSupplyPurchaseValidation", "bitNatureofSupplyStatus"], {}),
  },
  "serviceTaxHead": {
    key: "serviceTaxHead", label: "Taxation", menu: "Setup",
    table: "tblServiceTaxHead", pk: "intServiceTaxHeadID", titleField: "strServiceTaxHeadTaxfor",
    listColumns: ["strServiceTaxHeadTaxfor", "intBranchID", "intUserID"],
    fields: build("intServiceTaxHeadID", ["intServiceTaxHeadID", "dtServiceTaxHeadAppliedfrom", "strServiceTaxHeadTaxfor", "tintServiceTaxHeadTypeof", "intBranchID", "intUserID"], {"intBranchID": "dataLocking", "intUserID": "permission"}),
  },
  "airTicketsHead": {
    key: "airTicketsHead", label: "Air Tickets", menu: "Setup",
    table: "tblAirTicketsHead", pk: "intAirTicketsHeadID", titleField: "strAirTicketsHeadfor",
    listColumns: ["intAirTicketsHeadAccountID", "strAirTicketsHeadfor", "intBranchID", "intUserID"],
    fields: build("intAirTicketsHeadID", ["intAirTicketsHeadID", "intAirTicketsHeadAccountID", "dtAirTicketsHeadDate", "strAirTicketsHeadfor", "intBranchID", "intUserID", "tintAirTicketsHeadAction"], {"intBranchID": "dataLocking", "intUserID": "permission"}),
  },
  "rMDetail": {
    key: "rMDetail", label: "RM Detail", menu: "Setup",
    table: "tblRMDetailMaster", pk: "intRMDetailID", titleField: "strRMDetailfor",
    listColumns: ["intCRSID", "strRMDetailfor", "strRMDetailName"],
    fields: build("intRMDetailID", ["intRMDetailID", "intCRSID", "tintRMDetailfor", "strRMDetailfor", "strRMDetailName"], {"intCRSID": "cRS"}),
  },
  "accountSetupDetail": {
    key: "accountSetupDetail", label: "Account", menu: "Setup",
    table: "tblAccountSetupDetail", pk: "intAccountSetupHeadID", titleField: "strAccountSetupType",
    listColumns: ["intAccountSetupDetailID", "intHeadServiceID", "intDetailServiceID", "strAccountSetupType"],
    fields: build("intAccountSetupHeadID", ["intAccountSetupHeadID", "intAccountSetupDetailID", "intHeadServiceID", "intDetailServiceID", "strAccountSetupType", "strAccountSetupfor", "intAccountID", "bitAccountMandatory"], {"intAccountID": "account"}),
  },
  "voucherPrefix": {
    key: "voucherPrefix", label: "Voucher Prefix", menu: "Setup",
    table: "tblVoucherPrefixMaster", pk: "intVoucherPrefixID", titleField: "strVoucherPrefixfor",
    listColumns: ["intHeadServiceID", "intDetailServiceID", "strVoucherPrefixfor", "strVoucherPrefix"],
    fields: build("intVoucherPrefixID", ["intVoucherPrefixID", "intHeadServiceID", "intDetailServiceID", "strVoucherPrefixfor", "strVoucherPrefix", "intObjectID", "bitVoucherNumberDateWise", "strVoucherBranchPrefix", "intBranchID"], {"intObjectID": "object", "intBranchID": "dataLocking"}),
  },
  "voucherPrint": {
    key: "voucherPrint", label: "Voucher Print", menu: "Setup",
    table: "tblVoucherPrintMaster", pk: "intVoucherPrintID", titleField: "strVoucherPrintName",
    listColumns: ["intObjectID", "bitVoucherPrintSign", "bitVoucherPrintFooter", "strVoucherPrintName"],
    fields: build("intVoucherPrintID", ["intVoucherPrintID", "intObjectID", "tintVoucherPrintPaperType", "tintVoucherPrintPrintType", "tintVoucherPrintLogo", "bitVoucherPrintSign", "bitVoucherPrintFooter", "strVoucherPrintName", "strVoucherPrintTitle", "decVoucherPrintTop", "decVoucherPrintLeft", "decVoucherPrintRight", "decVoucherPrintBottom", "bitVoucherPrintDefault", "bitVouchereMailDefault", "strVoucherPrintTerms", "intBranchID"], {"intObjectID": "object", "intBranchID": "dataLocking"}),
  },
  "designReportHead": {
    key: "designReportHead", label: "Design Report", menu: "Setup",
    table: "tblDesignReportHead", pk: "intDesignReportHeadID", titleField: "strDesignReportName",
    listColumns: ["intObjectID", "strDesignReportName", "strDesignReportSubject", "intDesignReportOrder"],
    fields: build("intDesignReportHeadID", ["intDesignReportHeadID", "intObjectID", "tintDesignReportfor", "strDesignReportName", "strDesignReportSubject", "tintDesignReportUsing", "intDesignReportOrder", "strDesignReportQuery"], {"intObjectID": "object"}),
  },
  "caption": {
    key: "caption", label: "Caption", menu: "Setup",
    table: "tblCaptionMaster", pk: "intCaptionID", titleField: "strCaptionfor",
    listColumns: ["intServiceID", "intObjectID", "strCaptionfor", "strCaptionText"],
    fields: build("intCaptionID", ["intCaptionID", "intServiceID", "intObjectID", "strCaptionfor", "strCaptionText", "strCaptionTextReturn", "intBranchID"], {"intServiceID": "service", "intObjectID": "object", "intBranchID": "dataLocking"}),
  },
  "chequePrintHead": {
    key: "chequePrintHead", label: "Cheque Print", menu: "Setup",
    table: "tblChequePrintHead", pk: "intChequePrintHeadID", titleField: "strChequePrintHeadName",
    listColumns: ["intAccountID", "strChequePrintHeadName", "intChequePrintHeadTop", "intChequePrintHeadLeft"],
    fields: build("intChequePrintHeadID", ["intChequePrintHeadID", "intAccountID", "strChequePrintHeadName", "intChequePrintHeadTop", "intChequePrintHeadLeft", "intUserID", "bitChequePrintHeadLandscape", "bitChequePrintHeadDefault"], {"intAccountID": "account", "intUserID": "permission"}),
  },
  "eMailSetting": {
    key: "eMailSetting", label: "e-mail Setting", menu: "Setup",
    table: "tbleMailSetting", pk: "intBranchID", titleField: "strFromeMail",
    listColumns: ["strFromeMail", "strBCCeMail", "bitBCCOnUsereMail", "strMailServerName"],
    fields: build("intBranchID", ["intBranchID", "strFromeMail", "strBCCeMail", "bitBCCOnUsereMail", "strMailServerName", "intMailServerPort", "bitMailServerTLS", "strMailServerUser", "strMailServerPassword", "strSignHTML"], {}),
  },
  "smsSetting": {
    key: "smsSetting", label: "sms Setting", menu: "Setup",
    table: "tblsmsSetting", pk: "intBranchID", titleField: "strUrlSend",
    listColumns: ["strUrlSend", "strUrlDeliveryReport", "strUrlBalanceCheck", "strSenderID"],
    fields: build("intBranchID", ["intBranchID", "strUrlSend", "strUrlDeliveryReport", "strUrlBalanceCheck", "strSenderID", "strUserName", "strPassword", "tintNumberLength", "strSMSSign"], {}),
  },
  "whatsAppSetting": {
    key: "whatsAppSetting", label: "WhatsApp Setting", menu: "Setup",
    table: "tblWhatsAppSetting", pk: "intBranchID", titleField: "strWhatsAppNumber",
    listColumns: ["strWhatsAppNumber", "strWhatsAppURLTextSend", "intWhatsAppMessageQuantity", "intWhatsAppMessageUsed"],
    fields: build("intBranchID", ["intBranchID", "strWhatsAppNumber", "tintWhatsAppNumberLength", "strWhatsAppURLTextSend", "dtWhatsAppBalanceDate", "intWhatsAppMessageQuantity", "intWhatsAppMessageUsed", "strWhatsAppSign", "strWhatsAppToken"], {}),
  },
  "eInvoiceSettings": {
    key: "eInvoiceSettings", label: "E-Invoice Setting", menu: "Setup",
    table: "tblEInvoiceSettings", pk: "strProvider", titleField: "strProvider",
    listColumns: ["strParaName", "strParaValue", "intBranchID"],
    fields: build("strProvider", ["strProvider", "strParaName", "strParaValue", "intBranchID"], {"intBranchID": "dataLocking"}),
  },
  "reminderSetting": {
    key: "reminderSetting", label: "Reminder Setting", menu: "Setup",
    table: "tblReminderSetting", pk: "intReminderSettingID", titleField: "strReminderSettingfor",
    listColumns: ["strReminderSettingfor", "intReminderSettingDay"],
    fields: build("intReminderSettingID", ["intReminderSettingID", "strReminderSettingfor", "intReminderSettingDay"], {}),
  },
  "dataLocking": {
    key: "dataLocking", label: "Data Locking", menu: "Setup",
    table: "tblDataLocking", pk: "intBranchID", titleField: "intBranchID",
    listColumns: ["intDataLockingDay", "bitDataLocking", "bitDataHideing"],
    fields: build("intBranchID", ["intBranchID", "dtDataLockingDate", "intDataLockingDay", "bitDataLocking", "bitDataHideing", "dtDataLockingFinancialYearDate"], {}),
  },
};

export const refTitleField = (k) => MASTERS[k]?.titleField || 'name';
export const listMasters = () => Object.values(MASTERS).map((m) => ({ key: m.key, label: m.label, menu: m.menu }));